## DoS-Classifier

In [83]:
import pandas as pd
import numpy as np

In [84]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

PATH = 'SUEE1.csv'
PATH = '/home/tdokkad/Downloads/' + PATH

print("Loading SUEE1 dataset...")
df = pd.read_csv(PATH)
display(df)

slowloris = np.asarray(["10.128.0." + str(i) for i in range(1, 50)])
slowhttptest = np.asarray(["10.128.0." + str(i) for i in range(51, 100)])
slowloris_ng = np.asarray(["10.128.0." + str(i) for i in range(101, 150)])

# if you need separate index arrays for each group:
slowloris_i = np.unique(np.hstack([
    np.where(df["Source"].isin(slowloris)), 
    np.where(df["Destination"].isin(slowloris))]))
slowhttptest_i = np.unique(np.hstack([
    np.where(df["Source"].isin(slowhttptest)), 
    np.where(df["Destination"].isin(slowhttptest))]))
slowloris_ng_i = np.unique(np.hstack([
    np.where(df["Source"].isin(slowloris_ng)), 
    np.where(df["Destination"].isin(slowloris_ng))]))

# for ip in df["Source"].values:
#     if ip in slowloris:
#         df["Label"] = "slowloris"
#     elif ip in slowhttptest:
#         df["Label"] = "slowhttptest"
#     elif ip in slowloris_ng:
#         df["Label"] = "slowloris_ng"
#     else:
#         df["Label"] = "normal"

# for ip in df["Destination"].values:
#     if ip in slowloris:
#         df["Label"] = "slowloris"
#     elif ip in slowhttptest:
#         df["Label"] = "slowhttptest"
#     elif ip in slowloris_ng:
#         df["Label"] = "slowloris_ng"
#     else:
#         df["Label"] = "normal"

# Split samples into training and test sets
# feat_train, feat_test, y_train, y_test = train_test_split(
#     feat_all, y_all, test_size=0.4, random_state=0
# )


print(slowloris_i.shape)
print(slowhttptest_i.shape)
print(slowloris_ng_i.shape)
print("Completed.")

Loading SUEE1 dataset...

,No.,Time,Source,Destination,Protocol,Length,Info
0,1,0.000000,192.168.0.1,192.168.0.2,TCP,66,"80 > 39266 [FIN, ACK] Seq=1 Ack=1 Win=235 Le..."
1,2,0.038679,192.168.0.2,192.168.0.1,TCP,66,39266 > 80 [ACK] Seq=1 Ack=2 Win=245 Len=0 T...
2,3,0.156902,192.168.0.1,192.168.0.3,TCP,54,"80 > 9784 [FIN, ACK] Seq=1 Ack=1 Win=237 Len=0"
3,4,0.158266,192.168.0.3,192.168.0.1,TCP,54,9784 > 80 [ACK] Seq=1 Ack=2 Win=254 Len=0
4,5,0.593252,192.168.0.1,192.168.0.4,TCP,66,"80 > 62170 [FIN, ACK] Seq=1 Ack=1 Win=235 Le..."
...,...,...,...,...,...,...,...
2089431,2089432,464.968751,192.168.0.8,192.168.0.1,TCP,66,[TCP ACKed unseen segment] [TCP Previous segme...
2089432,2089433,465.155756,192.168.0.15,192.168.0.1,TCP,54,[TCP ACKed unseen segment] [TCP Previous segme...
2089433,2089434,465.888553,192.168.0.1,192.168.6.139,TCP,66,"80 > 42640 [PSH, ACK] Seq=1 Ack=468 Win=3008..."
2089434,2089435,466.022984,192.168.0.7,192.168.0.1,TCP,74,[TCP Port numbers reused] 48110 > 80 [SYN] S...
2089435,2089436,466.023007,192.168.0.1,192.168.0.7,TCP,74,"80 > 48110 [SYN, ACK] Seq=0 Ack=1 Win=28960 ..."

(2204,)
(6586,)
(17702,)
Completed.

In [85]:
X = df.copy()

HOST_ADDRESS = '192.168.0.1'
ATTACKER_PREFIX = '10.128'

# Features to mark whether traffic is outbound or inbound. 
X['Inbound'] = (X['Destination'] == HOST_ADDRESS)
X['Outbound'] = (X['Source'] == HOST_ADDRESS)

# Extract labels -- 'True' if malicious (prefixed with 10... instead of 192...)
y = np.logical_or(
    X['Source'].to_numpy().astype('U6') == ATTACKER_PREFIX,
    X['Destination'].to_numpy().astype('U6') == ATTACKER_PREFIX)

# TODO: Record an 'id' column for different clients, randomized between benign and attacker traffic? or remove entirely

X.drop(['Source', 'Destination'], axis=1, inplace=True)

display(X)

,No.,Time,Protocol,Length,Info,Inbound,Outbound
0,1,0.000000,TCP,66,"80 > 39266 [FIN, ACK] Seq=1 Ack=1 Win=235 Le...",False,True
1,2,0.038679,TCP,66,39266 > 80 [ACK] Seq=1 Ack=2 Win=245 Len=0 T...,True,False
2,3,0.156902,TCP,54,"80 > 9784 [FIN, ACK] Seq=1 Ack=1 Win=237 Len=0",False,True
3,4,0.158266,TCP,54,9784 > 80 [ACK] Seq=1 Ack=2 Win=254 Len=0,True,False
4,5,0.593252,TCP,66,"80 > 62170 [FIN, ACK] Seq=1 Ack=1 Win=235 Le...",False,True
...,...,...,...,...,...,...,...
2089431,2089432,464.968751,TCP,66,[TCP ACKed unseen segment] [TCP Previous segme...,True,False
2089432,2089433,465.155756,TCP,54,[TCP ACKed unseen segment] [TCP Previous segme...,True,False
2089433,2089434,465.888553,TCP,66,"80 > 42640 [PSH, ACK] Seq=1 Ack=468 Win=3008...",False,True
2089434,2089435,466.022984,TCP,74,[TCP Port numbers reused] 48110 > 80 [SYN] S...,True,False
2089435,2089436,466.023007,TCP,74,"80 > 48110 [SYN, ACK] Seq=0 Ack=1 Win=28960 ...",False,True

In [86]:
# Split X by protocol
tcp_indices = X['Protocol'] == 'TCP'
X_tcp = X[tcp_indices]
y_tcp = y[tcp_indices]

http_indices = X['Protocol'] == 'HTTP'
X_http = X[http_indices]
y_http = y[http_indices]

print(f'{len(tcp_indices)} items use TCP; malicious proportion: {sum(y_tcp) / len(y_tcp)}')
print(f'{len(http_indices)} items use HTTP; malicious proportion: {sum(y_http) / len(y_http)}')

2089436 items use TCP; malicious proportion: 0.01291489420778149
2089436 items use HTTP; malicious proportion: 1.0

This is notable -- *none* of the traffic captured as HTTP is from benign addresses.

Since the information present in the dataset depends significantly on what protocol is used (many features can be extracted from the 'info' field, which is completely different depending on protocol), we can much more effectively analyze by splitting by protocol. Since only malicious HTTP traffic is recorded, the best analysis that any model can give of HTTP traffic is to mark it all as malicious.

It becomes apparent during further processing that some of the rows Wireshark categorizes as TCP

In [87]:
# Preview a random-ish set of 'info' content for each category
print('TCP:')
info = X_tcp['Info'].to_numpy()
for rand_index in np.random.randint(0, len(info), 15):
    print(info[rand_index])

print('HTTP:')
info = X_http['Info'].to_numpy()
for rand_index in np.random.randint(0, len(info), 15):
    print(info[rand_index])

TCP:
[TCP Previous segment not captured] 443  >  41360 [ACK] Seq=11334 Ack=1854 Win=33024 Len=0 TSval=481276204 TSecr=4933575
[TCP ACKed unseen segment] 44537  >  80 [ACK] Seq=1119 Ack=410258 Win=65535 Len=0
[TCP ACKed unseen segment] [TCP Previous segment not captured] 24304  >  80 [ACK] Seq=235 Ack=577 Win=30464 Len=0 TSval=1533363920 TSecr=488087286
41142  >  443 [RST] Seq=1181 Win=0 Len=0
[TCP ACKed unseen segment] 47156  >  80 [ACK] Seq=178 Ack=44805 Win=119040 Len=0 TSval=479772296 TSecr=718542263
[TCP Previous segment not captured] 80  >  44652 [ACK] Seq=1480438 Ack=1119 Win=32160 Len=0
[TCP Previous segment not captured] 443  >  45384 [PSH, ACK] Seq=4097 Ack=253 Win=30080 Len=0 TSval=496669469 TSecr=1225202259
[TCP ACKed unseen segment] [TCP Previous segment not captured] 47716  >  80 [ACK] Seq=760 Ack=1274 Win=8127 Len=0
[TCP Previous segment not captured] 80  >  55650 [ACK] Seq=47701 Ack=196 Win=30080 Len=0 TSval=719269913 TSecr=481591422
[TCP Previous segment not captured] 80  >  41030 [ACK] Seq=40341 Ack=178 Win=30080 Len=0 TSval=720638066 TSecr=485011800
[TCP ACKed unseen segment] 56930  >  80 [ACK] Seq=196 Ack=12889 Win=55296 Len=0 TSval=493081348 TSecr=723865883
[TCP ACKed unseen segment] 80  >  63549 [ACK] Seq=1 Ack=365 Win=30336 Len=0
[TCP Dup ACK 770890#1] 80  >  38024 [PSH, ACK] Seq=1 Ack=369 Win=30016 Len=0
[TCP ACKed unseen segment] 80  >  43420 [ACK] Seq=1 Ack=196 Win=30080 Len=0 TSval=720997971 TSecr=485911563
[TCP ACKed unseen segment] 45897  >  80 [ACK] Seq=1119 Ack=2335998 Win=65535 Len=0
HTTP:
GET /bcrypt.php HTTP/1.1
HTTP/1.1 400 Bad Request  (text/html)
GET /bcrypt.php HTTP/1.1
HTTP/1.1 400 Bad Request  (text/html)
[TCP Retransmission] GET /bcrypt.php HTTP/1.1
GET /bcrypt.php HTTP/1.1
HTTP/1.1 200 OK  (text/html)
GET /bcrypt.php HTTP/1.1
GET /bcrypt.php HTTP/1.1
HTTP/1.1 400 Bad Request  (text/html)
HTTP/1.1 400 Bad Request  (text/html)
HTTP/1.1 400 Bad Request  (text/html)
HTTP/1.1 400 Bad Request  (text/html)
GET /bcrypt.php HTTP/1.1
GET /bcrypt.php HTTP/1.1

In [88]:
# Break down 'info' field into structured format

# Extract bracketed arguments from start of string
def extract_front_bracketed(str):
    pre_args = []
    while str[0] == '[':
        pre_arg, str = str[1:].split(']', 1)
        pre_args.append(pre_arg)
        str = str.lstrip()
    
    return pre_args, str

# Extract bracketed arguments from end of string
def extract_hind_bracketed(str):
    post_args = []
    while str[-1] == ']':
        str, post_arg = str[:-1].split('[', 1)
        post_args.append(post_arg)
        str = str.rstrip()
    
    return post_args[::-1], str

# Process 'Info' field of converted PCAP CSV
def process_info_tcp(info):
    copy = info

    # Additional logic for handling http-via-tcp:
    if '  >  ' not in info:
        # print(info)
        return None

    pre_args, info = extract_front_bracketed(info)
    
    # Source and destination port numbers (TODO: make sure these are being interpreted correctly)
    if len(info.split('  >  ', 1)) < 2:
        print(copy)
    source_port, info = info.split('  >  ', 1)
    dest_port, info = info.split(' ', 1)
    source_port = int(source_port)
    dest_port = int(dest_port)

    # Middle bracketed arguments
    mid_args, info = extract_front_bracketed(info)
    if len(mid_args) > 0:
        assert(len(mid_args) == 1)
        mid_args = mid_args[0].split(', ')

    # End bracketed arguments
    post_args, info = extract_hind_bracketed(info)

    vars = {}
    for var in info.split(' '):
        if '=' in var:
            k, v = var.split('=')
        else:
            k, v = var, 0
        vars[k] = int(v)

    return (pre_args, source_port, dest_port, mid_args, vars, post_args)

# Preview a random-ish set of 'info' content
# a = [process_info_tcp(info) for info in X_tcp['Info']]

# print(a[-10:])

# print(process_info(1))

We had to modify this code because some of the packets labeled as TCP still format their 'info' fields like the HTTP messages. Next we try looking at all of these messages.

In [89]:
http_rows_in_Xtcp = []
info = X_tcp['Info'].to_numpy()
for i in range(len(X_tcp)):
    if (process_info_tcp(info[i]) == None):
        http_rows_in_Xtcp.append(i)

In [90]:
X_mislabeled = X_tcp.iloc[http_rows_in_Xtcp] # Offset is required to target the right values
display(X_mislabeled)

y_mislabeled = y_tcp[http_rows_in_Xtcp]

print(f'{len(http_rows_in_Xtcp)} items are labeled TCP but have HTTP-style \'Info\' fields; \
malicious proportion: {sum(y_mislabeled) / len(y_mislabeled)}')

,No.,Time,Protocol,Length,Info,Inbound,Outbound
100163,100164,413.852056,TCP,164,HTTP/1.1 200 OK [TCP PDU reassembled in 100164],False,False
100566,100567,414.969776,TCP,164,HTTP/1.1 200 OK [TCP PDU reassembled in 100567],False,False
100592,100593,415.975408,TCP,164,HTTP/1.1 200 OK [TCP PDU reassembled in 100593],False,False
100597,100598,415.976600,TCP,164,HTTP/1.1 200 OK [TCP PDU reassembled in 100598],False,False
100967,100968,416.987761,TCP,164,HTTP/1.1 200 OK [TCP PDU reassembled in 100968],False,False
...,...,...,...,...,...,...,...
125253,125254,-3641.850490,TCP,55,GET /?1593 HTTP/1.1 [TCP PDU reassembled in 1...,False,False
125275,125276,-3641.702004,TCP,55,GET /?140 HTTP/1.1 [TCP PDU reassembled in 12...,False,False
125295,125296,-3641.616037,TCP,55,GET /?1807 HTTP/1.1 [TCP PDU reassembled in 1...,False,False
125317,125318,-3640.831660,TCP,55,GET /?1497 HTTP/1.1 [TCP PDU reassembled in 1...,False,False
125339,125340,-3640.592695,TCP,55,GET /?1196 HTTP/1.1 [TCP PDU reassembled in 1...,False,False

125 items are labeled TCP but have HTTP-style 'Info' fields; malicious proportion: 1.0

Like the items that Wireshark does label as HTTP, none of these are from benign traffic.
We will move them to the HTTP dataset, so that we can make use of more features from the genuine TCP datasets. If we had any benign data in the HTTP group, we could train a seperate classifier but the best we can do with our current data is predict '1' every time.

In [92]:
X_http = pd.concat([X_http, X_mislabeled])
y_http = np.concatenate([y_http, y_mislabeled])

# In X_tcp need to convert row numbers to indices for drop()
X_tcp.drop([X_tcp.iloc[i, 0] for i in http_rows_in_Xtcp])
y_tcp = np.delete(y_tcp, http_rows_in_Xtcp)